[workspace]
members = ["projects/*"]
default-members = [
    "projects/terrain-core",
    "projects/terrain-ds",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
